apiVersion: v1
items:
- apiVersion: keycloak.org/v1alpha1
  kind: Keycloak
  metadata:
    annotations:
      argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
      argocd.argoproj.io/sync-wave: "3"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"keycloak.org/v1alpha1","kind":"Keycloak","metadata":{"annotations":{"argocd.argoproj.io/sync-options":"SkipDryRunOnMissingResource=true","argocd.argoproj.io/sync-wave":"3"},"labels":{"app":"sso-noprod","app.kubernetes.io/instance":"sso-gcp-ocp-noprod"},"name":"keycloak","namespace":"sso-noprod"},"spec":{"extensions":["http://sso-theme-httpd-svc:8080/clh-theme-latest.jar"],"externalAccess":{"enabled":true},"instances":1,"keycloakDeploymentSpec":{"experimental":{"env":[{"name":"JAVA_INITIAL_MEM_RATIO","value":"50"},{"name":"JAVA_MAX_MEM_RATIO","value":"80"},{"name":"TZ","value":"America/Santiago"}]},"imagePullPolicy":"Always","resources":{"limits":{"memory":"2Gi"},"requests":{"memory":"1Gi"}}},"postgresDeploymentSpec":{"imagePullPolicy":"Always"},"profile":"RHSSO"}}
    creationTimestamp: "2024-01-31T21:46:05Z"
    generation: 7
    labels:
      app: sso-noprod
      app.kubernetes.io/instance: sso-gcp-ocp-noprod
    name: keycloak
    namespace: sso-noprod
    resourceVersion: "152565864"
    uid: 3f95cbd7-aa83-4561-add8-26cba88d49b8
  spec:
    extensions:
    - http://sso-theme-httpd-svc:8080/clh-theme-latest.jar
    externalAccess:
      enabled: true
    instances: 1
    keycloakDeploymentSpec:
      experimental:
        env:
        - name: JAVA_INITIAL_MEM_RATIO
          value: "50"
        - name: JAVA_MAX_MEM_RATIO
          value: "80"
        - name: TZ
          value: America/Santiago
      imagePullPolicy: Always
      resources:
        limits:
          memory: 2Gi
        requests:
          memory: 1Gi
    postgresDeploymentSpec:
      imagePullPolicy: Always
    profile: RHSSO
  status:
    credentialSecret: credential-keycloak
    externalURL: https://keycloak-sso-noprod.apps.gcp-ocp-noprod.losheroes.int
    internalURL: https://keycloak.sso-noprod.svc:8443
    message: ""
    phase: reconciling
    ready: true
    secondaryResources:
      ConfigMap:
      - keycloak-probes
      Deployment:
      - keycloak-postgresql
      PersistentVolumeClaim:
      - keycloak-postgresql-claim
      PrometheusRule:
      - keycloak
      Route:
      - keycloak
      - keycloak-metrics-rewrite
      Secret:
      - credential-keycloak
      - keycloak-db-secret
      Service:
      - keycloak-postgresql
      - keycloak
      - keycloak-discovery
      - keycloak-monitoring
      ServiceMonitor:
      - keycloak-service-monitor
      StatefulSet:
      - keycloak
    version: main
kind: List
metadata:
  resourceVersion: ""
