apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"creationTimestamp":null,"name":"sso-noprod"},"spec":{},"status":{}}
    openshift.io/sa.scc.mcs: s0:c29,c14
    openshift.io/sa.scc.supplemental-groups: 1000840000/10000
    openshift.io/sa.scc.uid-range: 1000840000/10000
  creationTimestamp: "2024-01-31T21:44:31Z"
  labels:
    kubernetes.io/metadata.name: sso-noprod
    olm.operatorgroup.uid/88389ca6-d8dc-414b-a660-2c32ee1a3087: ""
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.24
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.24
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:pod-security.kubernetes.io/audit: {}
          f:pod-security.kubernetes.io/audit-version: {}
          f:pod-security.kubernetes.io/warn: {}
          f:pod-security.kubernetes.io/warn-version: {}
    manager: pod-security-admission-label-synchronization-controller
    operation: Apply
    time: "2024-01-31T21:44:31Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:kubernetes.io/metadata.name: {}
    manager: argocd-controller
    operation: Update
    time: "2024-01-31T21:44:31Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:openshift.io/sa.scc.mcs: {}
          f:openshift.io/sa.scc.supplemental-groups: {}
          f:openshift.io/sa.scc.uid-range: {}
    manager: cluster-policy-controller
    operation: Update
    time: "2024-01-31T21:44:31Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:olm.operatorgroup.uid/88389ca6-d8dc-414b-a660-2c32ee1a3087: {}
    manager: olm
    operation: Update
    time: "2024-01-31T21:45:15Z"
  name: sso-noprod
  resourceVersion: "51038584"
  uid: f8c16f9e-f710-4faa-9d59-d313d14d7fa6
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
