---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.129.2.193/23"],"mac_address":"0a:58:0a:81:02:c1","gateway_ips":["10.129.2.1"],"routes":[{"dest":"10.128.0.0/14","nextHop":"10.129.2.1"},{"dest":"172.30.0.0/16","nextHop":"10.129.2.1"},{"dest":"100.64.0.0/16","nextHop":"10.129.2.1"}],"ip_address":"10.129.2.193/23","gateway_ip":"10.129.2.1"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.129.2.193"
          ],
          "mac": "0a:58:0a:81:02:c1",
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2024-03-28T20:13:54Z"
  generateName: keycloak-
  labels:
    app: keycloak
    com.company: Red_Hat
    component: keycloak
    controller-revision-hash: keycloak-5d8f9c8ff9
    rht.comp: SSO
    rht.comp_ver: 7.6.7
    rht.prod_name: Red_Hat_Runtimes
    rht.prod_ver: 2024_Q1
    rht.subcomp: SSO_Server
    rht.subcomp_t: application
    statefulset.kubernetes.io/pod-name: keycloak-0
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:k8s.ovn.org/pod-networks: {}
    manager: gcp-ocp-noprod-xtlzt-worker-b-6pj6r
    operation: Update
    subresource: status
    time: "2024-03-28T20:13:54Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
          f:com.company: {}
          f:component: {}
          f:controller-revision-hash: {}
          f:rht.comp: {}
          f:rht.comp_ver: {}
          f:rht.prod_name: {}
          f:rht.prod_ver: {}
          f:rht.subcomp: {}
          f:rht.subcomp_t: {}
          f:statefulset.kubernetes.io/pod-name: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"3acd5e88-ab2d-4fcb-8951-5140f5fe3f35"}: {}
      f:spec:
        f:affinity:
          .: {}
          f:podAntiAffinity:
            .: {}
            f:preferredDuringSchedulingIgnoredDuringExecution: {}
        f:containers:
          k:{"name":"keycloak"}:
            .: {}
            f:env:
              .: {}
              k:{"name":"CACHE_OWNERS_AUTH_SESSIONS_COUNT"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"CACHE_OWNERS_COUNT"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"DB_DATABASE"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"DB_JNDI"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"DB_PASSWORD"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:secretKeyRef: {}
              k:{"name":"DB_SCHEMA"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"DB_SERVICE_PREFIX_MAPPING"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"DB_USERNAME"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:secretKeyRef: {}
              k:{"name":"JAVA_INITIAL_MEM_RATIO"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"JAVA_MAX_MEM_RATIO"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"JGROUPS_PING_PROTOCOL"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"OPENSHIFT_DNS_PING_SERVICE_NAME"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"SSO_ADMIN_PASSWORD"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:secretKeyRef: {}
              k:{"name":"SSO_ADMIN_USERNAME"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:secretKeyRef: {}
              k:{"name":"STATISTICS_ENABLED"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"TX_DATABASE_PREFIX_MAPPING"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"TZ"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"X509_CA_BUNDLE"}:
                .: {}
                f:name: {}
                f:value: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:livenessProbe:
              .: {}
              f:exec:
                .: {}
                f:command: {}
              f:failureThreshold: {}
              f:initialDelaySeconds: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":8080,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:protocol: {}
              k:{"containerPort":8443,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:protocol: {}
              k:{"containerPort":8778,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:protocol: {}
              k:{"containerPort":9990,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:protocol: {}
            f:readinessProbe:
              .: {}
              f:exec:
                .: {}
                f:command: {}
              f:failureThreshold: {}
              f:initialDelaySeconds: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:memory: {}
              f:requests:
                .: {}
                f:memory: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/etc/x509/https"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/mnt/rh-sso"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/opt/eap/standalone/deployments"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/probes"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:hostname: {}
        f:initContainers:
          .: {}
          k:{"name":"extensions-init"}:
            .: {}
            f:env:
              .: {}
              k:{"name":"KEYCLOAK_EXTENSIONS"}:
                .: {}
                f:name: {}
                f:value: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:memory: {}
              f:requests:
                .: {}
                f:memory: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/opt/extensions"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
        f:volumes:
          .: {}
          k:{"name":"keycloak-extensions"}:
            .: {}
            f:emptyDir: {}
            f:name: {}
          k:{"name":"keycloak-probes"}:
            .: {}
            f:configMap:
              .: {}
              f:defaultMode: {}
              f:name: {}
            f:name: {}
          k:{"name":"sso-probe-netrc-volume"}:
            .: {}
            f:emptyDir:
              .: {}
              f:medium: {}
            f:name: {}
          k:{"name":"sso-x509-https-secret"}:
            .: {}
            f:name: {}
            f:secret:
              .: {}
              f:defaultMode: {}
              f:optional: {}
              f:secretName: {}
    manager: kube-controller-manager
    operation: Update
    time: "2024-03-28T20:13:54Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:k8s.v1.cni.cncf.io/network-status: {}
    manager: multus-daemon
    operation: Update
    subresource: status
    time: "2024-03-28T20:13:54Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:initContainerStatuses: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.129.2.193"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    subresource: status
    time: "2024-03-28T20:14:55Z"
  name: keycloak-0
  namespace: sso-noprod
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: keycloak
    uid: 3acd5e88-ab2d-4fcb-8951-5140f5fe3f35
  resourceVersion: "152565229"
  uid: b1f6e720-a4a7-4003-bff2-937b6e652e15
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - keycloak
          topologyKey: topology.kubernetes.io/zone
        weight: 100
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - keycloak
          topologyKey: kubernetes.io/hostname
        weight: 90
  containers:
  - env:
    - name: JAVA_INITIAL_MEM_RATIO
      value: "50"
    - name: JAVA_MAX_MEM_RATIO
      value: "80"
    - name: TZ
      value: America/Santiago
    - name: DB_SERVICE_PREFIX_MAPPING
      value: keycloak-postgresql=DB
    - name: TX_DATABASE_PREFIX_MAPPING
      value: keycloak-postgresql=DB
    - name: DB_JNDI
      value: java:jboss/datasources/KeycloakDS
    - name: DB_SCHEMA
      value: public
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          key: POSTGRES_USERNAME
          name: keycloak-db-secret
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: POSTGRES_PASSWORD
          name: keycloak-db-secret
    - name: DB_DATABASE
      value: root
    - name: JGROUPS_PING_PROTOCOL
      value: dns.DNS_PING
    - name: OPENSHIFT_DNS_PING_SERVICE_NAME
      value: keycloak-discovery.sso-noprod.svc.cluster.local
    - name: CACHE_OWNERS_COUNT
      value: "2"
    - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
      value: "2"
    - name: SSO_ADMIN_USERNAME
      valueFrom:
        secretKeyRef:
          key: ADMIN_USERNAME
          name: credential-keycloak
    - name: SSO_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          key: ADMIN_PASSWORD
          name: credential-keycloak
    - name: X509_CA_BUNDLE
      value: /var/run/secrets/kubernetes.io/serviceaccount/*.crt
    - name: STATISTICS_ENABLED
      value: "TRUE"
    image: registry.redhat.io/rh-sso-7/sso76-openshift-rhel8@sha256:21033463e761a6ff142551fa93ec20196ad46f18b0dc4a0c692866d4410c64ce
    imagePullPolicy: Always
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - /probes/liveness_probe.sh
      failureThreshold: 10
      initialDelaySeconds: 30
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 22
    name: keycloak
    ports:
    - containerPort: 8443
      protocol: TCP
    - containerPort: 8080
      protocol: TCP
    - containerPort: 9990
      protocol: TCP
    - containerPort: 8778
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - /probes/readiness_probe.sh
      failureThreshold: 10
      initialDelaySeconds: 40
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 22
    resources:
      limits:
        memory: 2Gi
      requests:
        memory: 1Gi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000840000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/x509/https
      name: sso-x509-https-secret
    - mountPath: /opt/eap/standalone/deployments
      name: keycloak-extensions
    - mountPath: /probes
      name: keycloak-probes
    - mountPath: /mnt/rh-sso
      name: sso-probe-netrc-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-469hl
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: keycloak-0
  imagePullSecrets:
  - name: default-dockercfg-52cwq
  initContainers:
  - env:
    - name: KEYCLOAK_EXTENSIONS
      value: http://sso-theme-httpd-svc:8080/clh-theme-latest.jar
    image: registry.redhat.io/rh-sso-7/sso7-rhel8-init-container@sha256:c9634cf64e2b0c3a7e8314b870dba12bb6a370b44545f9347ca577f7a5a13103
    imagePullPolicy: Always
    name: extensions-init
    resources:
      limits:
        memory: 2Gi
      requests:
        memory: 1Gi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000840000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/extensions
      name: keycloak-extensions
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-469hl
      readOnly: true
  nodeName: gcp-ocp-noprod-xtlzt-worker-b-6pj6r
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000840000
    seLinuxOptions:
      level: s0:c29,c14
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: sso-x509-https-secret
    secret:
      defaultMode: 420
      optional: true
      secretName: sso-x509-https-secret
  - emptyDir: {}
    name: keycloak-extensions
  - configMap:
      defaultMode: 365
      name: keycloak-probes
    name: keycloak-probes
  - emptyDir:
      medium: Memory
    name: sso-probe-netrc-volume
  - name: kube-api-access-469hl
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-03-28T20:13:57Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-03-28T20:14:55Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-03-28T20:14:55Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-03-28T20:13:54Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://49b9ce0937122dd1e3513b9281c7b55b011be66cb86552e721b7325933db5e50
    image: registry.redhat.io/rh-sso-7/sso76-openshift-rhel8@sha256:21033463e761a6ff142551fa93ec20196ad46f18b0dc4a0c692866d4410c64ce
    imageID: registry.redhat.io/rh-sso-7/sso76-openshift-rhel8@sha256:1cde6dbbee3aa25be767953c45670d4c2592d61a7af776e7e0d0d1b08a1d23ab
    lastState: {}
    name: keycloak
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-03-28T20:13:58Z"
  hostIP: 10.85.24.131
  initContainerStatuses:
  - containerID: cri-o://024082437ac546f30b23233055c206a54fd05e5bca34538ee351a18a6d90eebd
    image: registry.redhat.io/rh-sso-7/sso7-rhel8-init-container@sha256:c9634cf64e2b0c3a7e8314b870dba12bb6a370b44545f9347ca577f7a5a13103
    imageID: registry.redhat.io/rh-sso-7/sso7-rhel8-init-container@sha256:696f80a5e60fee24cccdf9844e11c244141b7c3cbc82341692e2cc1c1ecf3b4a
    lastState: {}
    name: extensions-init
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: cri-o://024082437ac546f30b23233055c206a54fd05e5bca34538ee351a18a6d90eebd
        exitCode: 0
        finishedAt: "2024-03-28T20:13:56Z"
        reason: Completed
        startedAt: "2024-03-28T20:13:55Z"
  phase: Running
  podIP: 10.129.2.193
  podIPs:
  - ip: 10.129.2.193
  qosClass: Burstable
  startTime: "2024-03-28T20:13:54Z"
