---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's https port.
      service.alpha.openshift.io/serving-cert-secret-name: sso-x509-https-secret
      service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1703103843
      service.beta.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1703103843
    creationTimestamp: "2024-01-31T21:46:52Z"
    labels:
      app: keycloak
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:description: {}
            f:service.alpha.openshift.io/serving-cert-secret-name: {}
          f:labels:
            .: {}
            f:app: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"3f95cbd7-aa83-4561-add8-26cba88d49b8"}: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ipFamilyPolicy: {}
          f:ports:
            .: {}
            k:{"port":8443,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: keycloak-operator
      operation: Update
      time: "2024-01-31T21:46:52Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:service.alpha.openshift.io/serving-cert-signed-by: {}
            f:service.beta.openshift.io/serving-cert-signed-by: {}
      manager: service-ca-operator
      operation: Update
      time: "2024-01-31T21:46:52Z"
    name: keycloak
    namespace: sso-noprod
    ownerReferences:
    - apiVersion: keycloak.org/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Keycloak
      name: keycloak
      uid: 3f95cbd7-aa83-4561-add8-26cba88d49b8
    resourceVersion: "51040399"
    uid: 74ae055b-19be-4e6f-952e-5a84265c1323
  spec:
    clusterIP: 172.30.43.23
    clusterIPs:
    - 172.30.43.23
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: PreferDualStack
    ports:
    - name: keycloak
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      app: keycloak
      component: keycloak
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2024-01-31T21:46:52Z"
    labels:
      app: keycloak
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"3f95cbd7-aa83-4561-add8-26cba88d49b8"}: {}
        f:spec:
          f:clusterIP: {}
          f:internalTrafficPolicy: {}
          f:ipFamilyPolicy: {}
          f:ports:
            .: {}
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:publishNotReadyAddresses: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: keycloak-operator
      operation: Update
      time: "2024-01-31T21:46:52Z"
    name: keycloak-discovery
    namespace: sso-noprod
    ownerReferences:
    - apiVersion: keycloak.org/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Keycloak
      name: keycloak
      uid: 3f95cbd7-aa83-4561-add8-26cba88d49b8
    resourceVersion: "51040362"
    uid: f641bf80-5197-4df1-a22b-a3db1b3d71a3
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: PreferDualStack
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    publishNotReadyAddresses: true
    selector:
      app: keycloak
      component: keycloak
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The monitoring service for Prometheus
    creationTimestamp: "2024-01-31T21:46:52Z"
    labels:
      app: keycloak
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:description: {}
          f:labels:
            .: {}
            f:app: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"3f95cbd7-aa83-4561-add8-26cba88d49b8"}: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":9990,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: keycloak-operator
      operation: Update
      time: "2024-01-31T21:46:52Z"
    name: keycloak-monitoring
    namespace: sso-noprod
    ownerReferences:
    - apiVersion: keycloak.org/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Keycloak
      name: keycloak
      uid: 3f95cbd7-aa83-4561-add8-26cba88d49b8
    resourceVersion: "51040373"
    uid: 3dd72652-fec9-4e74-ae38-33a6a5d7aa33
  spec:
    clusterIP: 172.30.244.169
    clusterIPs:
    - 172.30.244.169
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: keycloak-monitoring
      port: 9990
      protocol: TCP
      targetPort: 9990
    selector:
      app: keycloak
      component: keycloak
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2024-01-31T21:46:52Z"
    labels:
      app: keycloak
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"3f95cbd7-aa83-4561-add8-26cba88d49b8"}: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ipFamilyPolicy: {}
          f:ports:
            .: {}
            k:{"port":5432,"protocol":"TCP"}:
              .: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: keycloak-operator
      operation: Update
      time: "2024-01-31T21:46:52Z"
    name: keycloak-postgresql
    namespace: sso-noprod
    ownerReferences:
    - apiVersion: keycloak.org/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Keycloak
      name: keycloak
      uid: 3f95cbd7-aa83-4561-add8-26cba88d49b8
    resourceVersion: "51040348"
    uid: 2599f09a-9cbd-48ff-bec1-dcb004f0936b
  spec:
    clusterIP: 172.30.241.51
    clusterIPs:
    - 172.30.241.51
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: PreferDualStack
    ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: keycloak
      component: database
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2024-01-31T21:46:39Z"
    labels:
      monitoring-key: middleware
      name: rhsso-operator
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:monitoring-key: {}
            f:name: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"e0d4ec75-b189-45b7-b30e-970f1a88f5d9"}: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8383,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":8686,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: keycloak-operator
      operation: Update
      time: "2024-02-13T17:24:25Z"
    name: rhsso-operator-metrics
    namespace: sso-noprod
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: rhsso-operator
      uid: e0d4ec75-b189-45b7-b30e-970f1a88f5d9
    resourceVersion: "76904184"
    uid: 521723c2-3819-4f3d-968a-dac4bef4ca17
  spec:
    clusterIP: 172.30.77.72
    clusterIPs:
    - 172.30.77.72
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-metrics
      port: 8383
      protocol: TCP
      targetPort: 8383
    - name: cr-metrics
      port: 8686
      protocol: TCP
      targetPort: 8686
    selector:
      name: rhsso-operator
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"sso-theme-httpd-gcp-ocp-noprod"},"name":"sso-theme-httpd-svc","namespace":"sso-noprod"},"spec":{"ports":[{"port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"sso-theme-httpd"},"type":"ClusterIP"}}
    creationTimestamp: "2024-01-31T21:44:39Z"
    labels:
      app.kubernetes.io/instance: sso-theme-httpd-gcp-ocp-noprod
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: argocd-controller
      operation: Update
      time: "2024-01-31T21:44:39Z"
    name: sso-theme-httpd-svc
    namespace: sso-noprod
    resourceVersion: "51037842"
    uid: 2ac06202-c455-48c3-a834-c21e56535f66
  spec:
    clusterIP: 172.30.30.227
    clusterIPs:
    - 172.30.30.227
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: sso-theme-httpd
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: ServiceList
metadata:
  resourceVersion: "152573820"
