- name: Dynatrace 
  hosts: all
  sources:
    - name: dynatrace Saas
      dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: "{{ eda_host }}"
        dt_api_token: "{{ eda_token }}"
        delay: "{{ eda_delay }}"
  rules:
    - name: Dynatrace
      condition: event.title == "Test EDA"
      actions:
        - debug:
#       run_job_template:
#         name: "Hello World"
#         organization: "Default"
