- name: Dynatrace 
  hosts: all
  sources:
    - name: dynatrace Saas
      dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: "{{ eda_host }}"
        dt_api_token: "{{ eda_token }}"
        delay: "{{ eda_delay }}"
  rules:
    - name: Dynatrace
      condition:
        all:
         - event.title == "lnx-pilotomondata"
      action:
        run_job_template:
          name: "GoogleDrive_Token"
          organization: "BCI"



        
