- name: Dynatrace 
  hosts: all
  sources:
    - name: dynatrace Saas
      dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: "{{ eda_host }}"
        dt_api_token: "{{ eda_token }}"
        delay: "{{ eda_delay }}"
  rules:
    - name: Dynatrace
      condition:
        all:
         - event.title == "demo-alert" and event.recentComments.totalCount >= 0
      actions:
        - debug:
            var: event
        - run_job_template:
            name: "Hello World"
            organization: "Default"
            job_args:
              extra_vars:
                sdm: "{{ event.title }}"
