- name: expect
  hosts: localhost
  tasks:
  - name: expect 01
    ansible.builtin.expect:
      command: telnet {{ host }} {{ port }}
      responses:
        Enter\sChoice>:
          - "tacl\n"
      timeout: 10
    register: salida

  - name: debug
    debug:
      var: salida
