- name: expect
  hosts: localhost
  tasks:
  - name: expect 01
    ansible.builtin.expect:
      command: telnet {{ host }} {{ port }}
      echo: yes
      responses:
        "Enter Choice>" : "tacl"
        "TACL 1>": "logon super.super"
        "TACL 1>": "exit"
      timeout: 10
    register: salida

  - name: debug
    debug:
      var: salida
