- name: expect
  hosts: localhost
  tasks:
  - name: expect 01
    ansible.builtin.expect:
      command: telnet {{ tandem_host }} {{ tandem_port }}
      echo: true
      responses:
        (.*)Enter Choice>(.*) : "tacl\r"
        (.*)TACL 1>(.*) : "logon appansible\r"
        (.*)Password(.*) : '{{ tandem_password }}\r'
        (.*)$SYSTEM STARTUP 1>(.*) : "exit\r"
      timeout: 20
    register: salida
    ignore_errors: yes

  - name: debug
    debug:
      var: salida
