- name: expect
  hosts: localhost
  tasks:
  - name: expect 01
    ansible.builtin.expect:
      command: telnet {{ tandem_host }} {{ tandem_port }}
      echo: true
      responses:
        "(.*)Enter Choice>(.*)": 
          - "tacl"
        "(.*)TACL 1>(.*)": 
          - "logon {{tandem_user}}"
          - \n
        "(.*)Password(.*)": 
          - "{{tandem_password}}"
        "(.*)$SYSTEM STARTUP 1>(.*)": 
          - "exit"
      timeout: 20
    register: salida
    ignore_errors: yes

  - name: debug
    debug:
      var: salida
