- name: expect
  hosts: localhost
  tasks:
  - name: expect 01
    ansible.builtin.expect:
      command: telnet {{ host }} {{ port }}
      echo: true
      responses:
        (.*)Enter Choice>(.*) : tacl
        (.*)TACL 1>(.*) : logon super.super
        (.*)Password(.*) : test
        (.*)$SYSTEM STARTUP 1>(.*) : exit
      timeout: 20
    register: salida
    ignore_errors: yes

  - name: debug
    debug:
      var: salida
