- name: expect
  hosts: localhost
  tasks:
  - name: expect 01
    ansible.builtin.expect:
      command: telnet 
      responses:
        [>]: "tacl"
    register: salida

  - name: debug
    debug:
      var: salida
