- name: expect
  hosts: localhost
  tasks:
  - name: expect 01
    ansible.builtin.expect:
      command: telnet {{ host }} {{ port }}
      echo: yes
      responses:
        "Enter Choice>" : "tacl\n"
        "TACL 1>": "logon super.super\n"
      timeout: 20
    register: salida
    ignore_errors: yes

  - name: debug
    debug:
      var: salida
