- name: expect
  hosts: localhost
  tasks:
  - name: expect 01
    ansible.builtin.expect:
      command: telnet {{ host }} {{ port }}
      responses:
        Question:
          - tacl
    register: salida

  - name: debug
    debug:
      var: salida
