---
- name: Remediacion 02
  hosts: localhost
  tasks:
    - name: 'Remediacion 02 - Titulo Alerta: {{ dynatrace_event_title }} - ID: {{ dynatrace_event_id }}'
      debug: 
        msg: 'Se da comienzo a la Remediacion 02 - Titulo Alerta: {{ dynatrace_event_title }} - ID: {{ dynatrace_event_id }}'

    - name: 'Falla si es que variable force_error es true'
      fail:
        msg: 'Error forzado!'
      when: force_error
