---
- name: Telnet Tandem
  hosts: localhost
  tasks:
    - name: Prueba telnet
      ansible.netcommon.telnet:
        login_prompt: ''
        password_prompt: ''
        host: '{{ host }}'
        port: '{{ port }}'
        crlf: true
        prompts:
        - '(.*)Enter Choice>'
        - '(.*)TACL 1>'
        - '(.*)Password:'
        timeout: 15
        pause: 2
        command:
        - tacl
        - logon super.super
        - pass
        - exit
      register: salida  
        
    - name: debug
      debug: 
        var: salida
