---
- name: Telnet Tandem
  hosts: localhost
  tasks:
    - name: Prueba telnet
      ansible.netcommon.telnet:
        login_prompt: ''
        password_prompt: ''
        host: '{{ host }}'
        port: '{{ port }}'
        prompts:
        - ''
        timeout: 10
        pause: 5
        command:
        - exit
      register: salida  
        
    - name: debug
      debug: 
        var: salida
